<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Roberts\Leads\Models\LeadBusiness;

class CreateLeadsTable extends Migration
{
    public function up()
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->id();
            $table->string('lead_number')->index()->unique(); // Generated by system. This is identifier used to communicate about the quote request & for additional form pages.
            $table->string('email');
            $table->foreignIdFor(app('user'))->nullable(); // Can be added later if the email from the lead matches a user in the system
            $table->foreignIdFor(LeadBusiness::class); // moving to other table to reverse the relationship
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->string('position')->nullable();
            $table->string('phone_number')->nullable(); // Will be replaced later with relationship to Phone model in tipoff/addresses
            
            // Timestamps of when various processes completed. Will also have statuses added
            $table->dateTime('form_completed_at')->nullable();
            $table->dateTime('verified_at')->nullable();
            
                // Move these 3 fields to LeadBusiness table
                $table->boolean('current_plan_under_cancellation')->nullable();
                $table->date('current_plan_expires_at')->nullable();
                $table->text('past_comp_claims')->nullable();
            
            $table->foreignIdFor(app('user'), 'creator_id')->nullable(); // Will seldom be used, but is needed in case a lead is added by a staff member on behalf of a lead that called in.
            $table->foreignIdFor(app('user'), 'updater_id')->nullable(); // Most fields will be locked for updates in Nova, but we may allow some to be updated by staff.
            $table->timestamps();
        });
    }
}
