<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Roberts\WorkCompLeads\Models\WcBusiness;

class CreateWcLeadsTable extends Migration
{
    public function up()
    {
        Schema::create('wc_leads', function (Blueprint $table) {
            $table->id();
            $table->string('lead_number')->index()->unique(); // Generated by system. This is identifier used to communicate about the quote request & for additional form pages.
            $table->string('email');
            $table->foreignIdFor(WcBusiness::class);
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->string('position')->nullable();
            $table->string('phone_number')->nullable(); // Will be replaced later with relationship to Phone model in tipoff/addresses
            
            // Move these 3 fields to WcBusiness table
            $table->boolean('current_plan_under_cancellation')->nullable();
            $table->date('current_plan_expires_at')->nullable();
            $table->text('past_comp_claims')->nullable();
            
            $table->timestamps();
        });
    }
}
