<div class="onboarding-form">
    @if ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::PRESENTATION)
        @livewire('wc::onboarding-form.presentation', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::CONTACT_DETAILS)
        @livewire('wc::onboarding-form.contact-details', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::MAILING_ADDRESS)
        @livewire('wc::onboarding-form.mailing-address', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::BUSINESS_DETAILS)
        @livewire('wc::onboarding-form.business-details', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::PAYROLL_CLASSIFICATIONS)
        @livewire('wc::onboarding-form.payroll-classifications', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::COMP_INSURANCE_CHECK)
        @livewire('wc::onboarding-form.comp-insurance-check', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::COMP_INSURANCE)
        @livewire('wc::onboarding-form.comp-insurance', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::COMP_CLAIMS_CHECK)
        @livewire('wc::onboarding-form.comp-claims-check', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::COMP_CLAIMS)
        @livewire('wc::onboarding-form.comp-claims', ['lead' => $lead])
    @elseif ($step === \Roberts\WorkCompLeads\Enums\OnboardingFormStep::COMPLETED)
        @livewire('wc::onboarding-form.completed', ['lead' => $lead])
    @endif
</div>
